
@baseUrl = http://localhost:8080
# @baseUrl = https://deploy-rodas-e-motores.onrender.com

# Rota Base
GET  {{baseUrl}}/

### Usuario
POST {{baseUrl}}/usuario
Content-Type: application/json

{
  "nome": "Luciano",
  "cpf": "8888888",
  "telefone": "77777777",
  "email": "Luciano@gmail.com",
  "cidade": "Laje",
  "estado": "BA",
  "pais": "Russia",
  "bairro": "hfhfhfh",
  "endereco": "jdjdjkdjkdjdjkd"
}

###
POST {{baseUrl}}/singUp
Content-Type: application/json

{
  "usuarioId": "1",
  "usuario": "lucianoNeto",
  "senha": "123"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "usuario": "lucianoNeto",
  "senha": "123"
}

###
GET  {{baseUrl}}/buscar?id=1&nome=lucianoNeto
Content-Type: application/json

{
  "usuario": "lucianoNeto",
  "senha": "123"
}